### ISSUE TITLE
first feedback

### ISSUE THREAD

**Issue by mschorer** [gerritv/Grbl-Panel#1]
Yay, looking good - i'll give it a whirl tonight.

my 5ct from first looks:
- love the offsets tab!
- jogging and feed-radios don't keep their setting and i get an infinite "you have to select them" loop
- is there a "home" button somewhere?
- connect/port settings can be moved from front-panel to settings panel - "connect on load" does the job for me - bring a dialog to front only when there's no port/no grbl
- what screen size is it designed for? scaling the app only works vertically.
- does it remember window position (+size)
- the jogging is very sensitive (with a mouse) - it's hard to move just 1 unit. will test repeat rates @ real hardware
- what's the idea behind "special positions"? tool changing position etc

**Comment by gerritv** [comment]
Closing this.
 I investigated remembering location etc and it seems a lot of effort. Might revisit once other enhancements are completed.
Thank you for your inputs.
