### ISSUE TITLE
cannot read a CNC code for G02 ?

### ISSUE THREAD

**Issue by kuko71** [gerritv/Grbl-Panel#103]
Hi, I loaded NC code to GRBL panel, and it stops on this line:

G3 X6.667 Y5.556 I0 J5.556

ans shower Error.

Could you advice what is wrong on this line and why GRBL panel cannot understand it?

**Comment by gerritv** [comment]
GrblPanel only passes the gcode to Grbl, it does nothing with it. 
The Error number will give you the hint you need.  Just drag the column with Error in it to the right a bit to see the details.
You could also turn on Verbose and see what the error number is.

**Comment by kuko71** [comment]
Great thanks. I see that feed is undefined. Now it all work fine.
