### ISSUE TITLE
Is it possible to set jog distances directly?

### ISSUE THREAD

**Issue by wind-rider** [gerritv/Grbl-Panel#104]
I'm making a custom jog dial like on http://www.instructables.com/id/Custom-Mouse-Wheel-As-PocketNC-Jog-Wheel/. I'm adding a few extra knobs to it that should get the ability to e.g. select an axis or select the jog distance. My plan was to have the Arduino in it simulate keystrokes to control Grbl-Panel.

On https://github.com/gerritv/Grbl-Panel/wiki/Key-Mappings I saw that there are key mappings for movement in the various directions, but for the jog distance selection I see only previous / next commands instead of commands to select them directly.

Of course when connecting I can send a "previous" command keystroke 4 or 5 times to get it to a known state, but it would be more reliable if the distance could be set directly.

Is there an option for that?

**Comment by gerritv** [comment]
No but you could add some key mappings for Macros 2-5 to GrblGui.vb around line 219 and then add appropriate macros. 
If you wanted to actually add all the required combinations you would need to add the various keycode mappings in GrblGui.vb and then add code to handle them in GbrlJogging.vb . Not too difficult but not something I would do for general release.
