### ISSUE TITLE
Future Request for file name

### ISSUE THREAD

**Issue by wlaw** [gerritv/Grbl-Panel#107]
OK, so i'm working with my machine this morning and have 2 files to cut, left side and right side.
I just finished cutting one of them and was ready to cut the other. Is there a way for me to tell the file that just finished? :-) 

I have been looking for it and cant seem to see it. 
My wife says that's what I always say :-)

So, is it possible to add the filename that is loaded on the screen? Maybe next to Message.
![image](https://cloud.githubusercontent.com/assets/15525769/25305196/db7b11fc-2744-11e7-9d2d-f6b90bc2fdee.png)

Again, thanks for making Grbl-Panel so great.  

Kind Regards

Bill

**Comment by wlaw** [comment]
OK, so for now I added this to my VCARVE grbl post processor.
";[TP_FILENAME]"
This adds the file name at the top of the G CODE file.
![image](https://cloud.githubusercontent.com/assets/15525769/25361539/b4fe8e44-291c-11e7-964a-25977dfbafb4.png)

**Comment by gerritv** [comment]
I'm puzzled. Above the file control icons is the area where file name is supposed to be. Was it there when you loaded the file with the Folder icon? Since the Run/Start button is not highlighted I am guessing that you don't have a file loaded?

Also noticed that you must be using quite an old version, the new version has a Single Step icon next to Start/Run

**Comment by wlaw** [comment]
![image](https://cloud.githubusercontent.com/assets/15525769/25402439/b61755b8-29c6-11e7-8c0e-13ca75bcc7e5.png)

1.0.9.7 - A bit behind, but I get tired of loading the macro's I use all of the time.

**Comment by wlaw** [comment]
I guess 9.7 is a bit old, I will upgrade tonight and let you know.
I just hate to break something that's working :-)

Thanks for your help.

**Comment by gerritv** [comment]
Copy the user.config file from %localappdata%\GrblPanel 1.0.9.7 subdirectory to the new one created after you run the new copy first time.

**Comment by wlaw** [comment]
:-)

**Comment by wlaw** [comment]
I see it now!

Thanks @gerritv 

![image](https://cloud.githubusercontent.com/assets/15525769/25412814/91a6ea7c-29f3-11e7-8b8f-7c7175281683.png)
