### ISSUE TITLE
More Feedback

### ISSUE THREAD

**Issue by aeleus** [gerritv/Grbl-Panel#11]
Thanks for writing this. It is by far the best Grbl controller I've tried - simple, but powerful.

Here is some feedback after first use:

1. I downloaded what should be the latest version (https://github.com/gerritv/Grbl-Panel/releases/download/v1.0.1.0/GrblPanel-Release-1.0.1.0.zip), but Help, About and the properties for the exe still say 1.0.0.0.

2. It would be great to have the option to configure how many decimal places the position display reads and have it round to that. I'm running a Shapeoko 2 with Nema 23 motors. The fourth decimal place when in inches just means I have to constantly translate in my mind what the position is (e.g., "0.9997" = "1.000"). I'll never be able to use that level of precision.

3. I may have missed it, but keyboard shortcuts would be nice for elements that allow keyboard entry (e.g., Alt-M activates the cursor in Manual Command).

4. A configurable file extension filter when opening g-code files would be helpful.

5. After you load and run a g-code file, it's gone. I'd like to be able to rerun or reload it with a button.

As I said, great work. I'm not a developer, but I'd be happy to help test.

Thanks

**Comment by gerritv** [comment]
1, 4 and 5 are now checked in, V1.0.3.0
