### ISSUE TITLE
crash on usb unplug

### ISSUE THREAD

**Issue by ScottTu** [gerritv/Grbl-Panel#110]
unhandled error if you unplug the usb cord after being connected.

**Comment by gerritv** [comment]
I can't duplicate this.

**Comment by ScottTu** [comment]
next time it happens I'll get some more error info. I'm using a desktop cnc with an arduino controller.

**Comment by electrokean** [comment]
It is very likely dependant on the specific USB serial interface (FTDI, 16U2, CH340) and version of Windows driver you have.

**Comment by ScottTu** [comment]
could be, its not a critical bug but I've had it do it while resetting the machine or powering it off after cutting.

**Comment by ScottTu** [comment]
[error.txt](https://github.com/gerritv/Grbl-Panel/files/998969/error.txt)
win7 64, ch340 serial adapter on the arduino.

**Comment by gerritv** [comment]
I'll add an exception handler for Denied, that should take care of the issue.

**Comment by ScottTu** [comment]
thanks and thanks for the great program too.

**Comment by gerritv** [comment]
Fixed
