### ISSUE TITLE
Unhandled exception while connecting via USB

### ISSUE THREAD

**Issue by RSG88** [gerritv/Grbl-Panel#114]
Initial connection to a new controller,  I am also new to using Grbl-Panel, any advise?
![screenshot 2017-06-04 06 37 43](https://cloud.githubusercontent.com/assets/29175403/26761230/366ec57c-48f1-11e7-96ba-83868344b31a.png)
![screenshot 2017-06-04 06 43 26](https://cloud.githubusercontent.com/assets/29175403/26761232/36757e12-48f1-11e7-8bc7-36a6b24f27a2.png)
![screenshot 2017-06-04 06 43 34](https://cloud.githubusercontent.com/assets/29175403/26761231/367292c4-48f1-11e7-8d8f-6d1d0cd128e4.png)

**Comment by gerritv** [comment]
You are using an old version of Grbl-Panel with what I am guessing is Grbl 1.1.

**Comment by RSG88** [comment]
It is working now on latest revision, Thank You so much for your quick response and help!
