### ISSUE TITLE
Manually control stepper motor with joystick

### ISSUE THREAD

**Issue by Camerutttt** [gerritv/Grbl-Panel#115]
Hey I was wondering if it is possible to manually control a stepper motor with a joystick.

Right now, all I am able to do is to make the stepper motor turn for a certain number of revolutions when my joystick is pushed in a certain direction.

I want to make it such that the stepper motor will keep on turning for as long as I push my joystick and stop when I release my joystick.

**Comment by tklus** [comment]
I am currently using a joystick to run my machine and I can set the step distance to .1 inches and just hold the joystick and it will feed until I release the joystick.

there is a setting for the repeat rate when the joystick is held so you might be able to adjust that.

are you using the latest version of GRBL and GRBL Panel?

**Comment by Camerutttt** [comment]
I think I got the latest version since I just downloaded it today. 

Pardon me, but I am new to GRBL. So from what you have done, I assume you map your joystick to the computer arrow keys? Since that is how I do it. My joystick is the 1 with 4 switches, so when you push it in a particular direction, 1 of the switches will be activated. Also, all I have to do is change the distance to 0.1 inches and set it on repeat rate?

**Comment by tklus** [comment]
You are correct, I am just using a joystick and mapping to the key strokes. I will have to look at my repeat rates but that is something you can try.

**Comment by Camerutttt** [comment]
So all I have to do in the GRBL Panel is to adjust the distance to 0.1 like so: http://imgur.com/WMzKalX?

and to play around with the repeat rates and check the Enable keyboard arrows like so: http://imgur.com/9jYfjsr?

**Comment by tklus** [comment]
Yup, give it a shot. It works with my machine....

**Comment by Camerutttt** [comment]
Alright thanks for your help. Unfortunately, all my stuff arent with me right now so I will let you know how it goes later on.

**Comment by sonnylowe** [comment]
Wow, this is good stuff, thanks for sharing!!!

**Comment by tklus** [comment]
what key mapper are you using? that could be the issue as well. maybe there is a setting for repeat in that too.

I am using antimicro for my key mapping

**Comment by Camerutttt** [comment]
Hey I just tested it and it appears to be running quite smoothly. However, when I release the joystick, the stepper motor will still continue to run for a few seconds before stopping. So for this issue I should play around with the repeat rates?

I am using JoyToKey and yes, there is also a setting for repeat too.

**Comment by Camerutttt** [comment]
I have also attached another stepper motor for the other axis. So now I can control 1 stepper motor by moving the joystick in the x-axis and the 2nd stepper motor by moving the joystick in the y-axis. However, when I move the joystick diagonally, both stepper motors movement are very jerky.

**Comment by Camerutttt** [comment]
Also, is there a way to have a return to zero position button using an external switch?

**Comment by tklus** [comment]
You can set up macro buttons in GRBL Panel and maybe we can request to have these macro buttons mapped to certain keys on the keyboard.

**Comment by Camerutttt** [comment]
I know that I can set macro buttons but I am unsure of how to map them to my keyboard

**Comment by tklus** [comment]
This would be a feature we would need to request from Gerrit...

**Comment by Camerutttt** [comment]
So as of now there is no other way to do this? Maybe through something like UGS?

**Comment by gerritv** [comment]
Adding some more key codes is easy, can someone pick values? I have other features to add but those are taking a bit more thinking.

**Comment by tklus** [comment]
How about 1-9 number keys? or however many macro buttons are available, not sure off the top of my head how many there are.

Thanks for the support!
Tim

**Comment by gerritv** [comment]
Implemented, macros map to F2-F6
