### ISSUE TITLE
Will only run single block

### ISSUE THREAD

**Issue by tbucket32** [gerritv/Grbl-Panel#117]
When I load a .nc file, it shows up in the window.  I hit RUN and nothing happens.  If I keep clicking single block it will execute.

**Comment by gerritv** [comment]
I can't reproduce that, when I load a file and press Start/Resume Sending the file starts up. Perhaps you have an alarm or error condition? That will show in the Status window and/or the Sts column of the GCode window.

**Comment by tbucket32** [comment]
When I press start it just sits there and does nothing. I see no alarms or errors.  I can let it sit 30 seconds and it does nothing. Its like it trys to send and is waiting for a response but gets nothing so it hangs. But single block is no issue.  Maybe I'll reinstall and try again

Casey Linn
On Jul 10, 2017, at 6:34 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

I can't reproduce that, when I load a file and press Start/Resume Sending the file starts up. Perhaps you have an alarm or error condition? That will show in the Status window and/or the Sts column of the GCode window.

**Comment by gerritv** [comment]
Is there anything in the Sts column after clicking Start/Resume? It should at least say Sent. A screenshot of GCode and Status sections would help me maybe see the reason.

**Comment by tbucket32** [comment]
It never says sent...status column is always blank. Ill try to get screen shots tonight or early tomorrow morning.

Casey Linn
On Jul 10, 2017, at 8:22 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there anything in the Sts column after clicking Start/Resume? It should at least say Sent. A screenshot of GCode and Status sections would help me maybe see the reason.

**Comment by tbucket32** [comment]
Attached is a picture of the screen after i have pushed start.

Casey Linn
On Jul 10, 2017, at 8:22 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there anything in the Sts column after clicking Start/Resume? It should at least say Sent. A screenshot of GCode and Status sections would help me maybe see the reason.

**Comment by tbucket32** [comment]
I just deleted the files and downloaded them again. Its doing the same thing.

Casey Linn
On Jul 10, 2017, at 8:22 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there anything in the Sts column after clicking Start/Resume? It should at least say Sent. A screenshot of GCode and Status sections would help me maybe see the reason.

**Comment by gerritv** [comment]
Unfortunately the screen shot didn't make it to Github :-(

**Comment by tbucket32** [comment]
Hopefully the picture works this time.
![20170710_191945](https://user-images.githubusercontent.com/30042153/28061099-4f954904-65f7-11e7-8324-3e44982bf373.jpg)

**Comment by gerritv** [comment]
it almost looks as if  the file has not finished loading, the File and Start icons should be darker. If light coloured then they are not enabled. I will look over the code later today

**Comment by tbucket32** [comment]
The code is only a couple lines. It draws a simple 5mm square box.

In the image, I had clicked the load button and selected the file then hit start....that is when the buttons when light coloured.

Casey Linn
On Jul 11, 2017, at 8:08 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

it almost looks as if the file has not finished loading, the File and Start icons should be darker. If light coloured then they are not enabled. I will look over the code later today

**Comment by tbucket32** [comment]
Could it be caused by only having gbrl 0.8?  Its a Laseraxe controller that has pins D11 & D12 hard wired for the old gbrl.

Casey Linn
On Jul 11, 2017, at 8:08 AM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

it almost looks as if the file has not finished loading, the File and Start icons should be darker. If light coloured then they are not enabled. I will look over the code later today

**Comment by gerritv** [comment]
Ah, yes I do not support Grbl 0.8 although usually the symptoms are more obvious. I should perhaps put something in the code to detect and warn users.

You should consider recompiling Grbl 1.1 with the pin settings reverted back to 0.8 layout. Changing #define VARIABLE_SPINDLE to a comment on line 339 of https://github.com/gnea/grbl/blob/master/grbl/config.h will swap the pins back to 0.8 layout.

**Comment by tbucket32** [comment]
If i do that, will i lose pwm control of the laser?

Casey Linn
On Jul 11, 2017, at 9:11 PM, Gerrit Visser <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah, yes I do not support Grbl 0.8 although usually the symptoms are more obvious. I should perhaps put something in the code to detect and warn users.

You should consider recompiling Grbl 1.1 with the pin settings reverted back to 0.8 layout. Changing #define VARIABLE_SPINDLE to a comment on line 339 of https://github.com/gnea/grbl/blob/master/grbl/config.h will swap the pins back to 0.8 layout.

**Comment by gerritv** [comment]
I am not sure what you would lose, if anything. PWM was added in 0.9 but the pin map had to change. So your board must already deal with that? 
Plan B would be to alter the cable(s) connecting to the board so it woks with 1.1 versions.
