### ISSUE TITLE
Typing in values for work offset

### ISSUE THREAD

**Issue by Legendaire** [gerritv/Grbl-Panel#12]
I know one may issue an gcode command to set the work offset to a value (as opposed to just zero).  I've been using probing to find the edges of my stock or vise depending on which I used in my CAM program.  I am using a feeler gauge with a wire attached to it and an alligator clip attached to the tool in the spindle.  I'd like to just be able to type in the value for an axis once the probe is done.  ie. if I am using a 1mm feeler gauge for setting z I'd like to be able to set the z axis to 1.  Right now I have to set it to 0 via the gui, move the x and y away from the part, move down 1mm and then reset to 0.  As an example, I know mach3 does this.

**Comment by gerritv** [comment]
I reviewed the http://home.comcast.net/~cncwoodworker/2010.html screenset, it has a decent implementation and a description of what you are looking for.
Not sure when I can implement this, I am away from my machine until at least June 2015 :-(

**Comment by Legendaire** [comment]
Yes, exactly like that.  One would just click on the text box next to X, Y,
or Z and type in a value.  I am not in any hurry for this to be put in.
It's just a bummer you have to be away from your machine for so long.

**Comment by gerritv** [comment]
@Legendaire Finally I implemented the main part of this request. The edge finding has to stil wait until I have a working machine, that might be a while yet.
