### ISSUE TITLE
NullReferenceException was unhandled

### ISSUE THREAD

**Issue by trietdao95** [gerritv/Grbl-Panel#121]
I want to compile the source code myself but there is a problem in GrblJogging.vb at line 24:
_gui.btnXPlus.Interval = 1000 / .JoggingXRepeat
It said NullReferenceException was unhandled. I'm using Visual Studio 2015. Hope you can help me with this issue
![image](https://user-images.githubusercontent.com/11796845/29467424-b6fed8b2-846a-11e7-81af-cbdbc4ab5f31.png)

**Comment by gerritv** [comment]
I used to use 2105, now 2017. I stepped through the code just now and don't get an exception. 

After you Stop debugging, is there a value/setting in Project/Settings for .JoggingXRepeat? Or is it btnXPlus that is Null?

**Comment by trietdao95** [comment]
I redownload the code and it works fine now. Thank you!

**Comment by gerritv** [comment]
Great news!
