### ISSUE TITLE
Feed Rates are base on? 

### ISSUE THREAD

**Issue by tiptonspiderj** [gerritv/Grbl-Panel#125]
gerritv,

I am new to using Grbl Panel and I can't find any documentation regarding the feed rate numbers next to the radio buttons.  Specifically I am looking for how you came up with the numbers for Metric...1000, 500, 100, and 5.  Any information would be much appreciated.

Sincerely,
Jeremy

**Comment by gerritv** [comment]
They are not unusual rates for jogging. Perhaps a misleading name, maybe should have used Jog Rates. The values can be altered to suit a particular situation on the Settings page.

**Comment by tiptonspiderj** [comment]
It's not the rates that confuse me, but why there is no correlation between the Metric values and the Imperial values for all four values.  I am a programmer looking at your code and there is no explanation of where the numbers come from.  What does the feed rate of 1000 stand for in Metric?  I understand you can change the reference in the settings page...I don't understand why the first three numbers correlate mathematically and the number 5 doesn't correspond.

**Comment by tiptonspiderj** [comment]
I am looking for how the Metric numbers correlate to the Imperial numbers for your feed rate calculations.

**Comment by gerritv** [comment]
They are just numbers. no correlation intended or expected between inferial and metric. The values are only used for jogging, so I choose values that seemed relevant to each measurement system.

**Comment by tiptonspiderj** [comment]
Your response makes no sense at all.  How can you say something should equal a value when you have no reference for it?

**Comment by tiptonspiderj** [comment]
I guess this goes towards your whole approach for programming with partial classes in visual basic.

**Comment by gerritv** [comment]
I'm not following your path in why the question relates to code. Feed rates are rates related to machine movement, chosen to accomplish some movement to jog to a location. Nothing to do with programming style.

**Comment by tiptonspiderj** [comment]
How can you say a default should be XXXX number when you don't know where the number comes from?

**Comment by tiptonspiderj** [comment]
You have already answered my question in the fact that you simply do not know.

**Comment by Sunnysky** [comment]
Feedrates are defined in the program and saved on exit. 
I used 60000 mm/min to get 1 m/s velocity 
What is it you need to understand?
