### ISSUE TITLE
Feature Request: Job Timer

### ISSUE THREAD

**Issue by NeoMorph** [gerritv/Grbl-Panel#126]
One thing I would like to do is time a job from start to finish and then log it with the file name of the G-Code so I know how long multiple jobs of the same part will take. Should be pretty simple... take the time code of when a job starts, take another time stamp when it finishes, calculate the time and then append the data to the file. 

Heck you could probably add it to the G-code file as a comment.

**Comment by gerritv** [comment]
GrblPanel presently displays elapsed time, that should give you the info you need.

**Comment by gerritv** [comment]
I would not like to code anything that modifies the Gcode file.
