### ISSUE TITLE
additional feedback

### ISSUE THREAD

**Issue by srsimmons** [gerritv/Grbl-Panel#14]
My laptop has a 1440x900 screen and cannot properly display the app.  I suspect this is due to the issues you list earlier with horizontal stretch, etc.  Anyway, it makes using the app difficult as the control box overlays and obscures the gcode box; the mdi box overlays the grbl box, both overlay the position box.  Also when not maximized, there is no scroll bar, but when maximized, there is.  Very odd.

Overall, a very nice start.  I particularly like the setting tab.  Other minor nits are already covered by yours and others comments and feedback.

Looking forward to the next release.

**Comment by gerritv** [comment]
Finally fixed in V1.0.3.0
