### ISSUE TITLE
Ignore async characters in gcode

### ISSUE THREAD

**Issue by tbfleming** [gerritv/Grbl-Panel#20]
Autodesk decided that GRBL needs a % at the top of the file (they probably were testing with UGS or another horribly buggy sender). This causes grbl-panel to stop; it won't resume. Could you detect and ignore async commands?

Sorry to flood you with reports suddenly. Even with these issues this is a really nice tool. I got tired of dealing with UGS lockups.

**Comment by gerritv** [comment]
Fixed in V1.0.3.0
