### ISSUE TITLE
How to set work coordinates

### ISSUE THREAD

**Issue by Scott216** [gerritv/Grbl-Panel#26]
In the offsets section of GRBL-panel, how do I send the entered offsets to GRBL?

**Comment by gerritv** [comment]
Hi Scott
After entering a value, e.g. G54 X, double click in that box to send the info to Grbl. This lets you change/set one axis at a time for each Offset. You can see the resulting Gcode in the gcode section. I will review the Wiki to ensure that this is clarified.

**Comment by Scott216** [comment]
Worked great, thanks
