### ISSUE TITLE
Version 1.0.5.0 reports as 1.0.3.0

### ISSUE THREAD

**Issue by aeleus** [gerritv/Grbl-Panel#32]
I've been testing the new build (1.0.5.0) and love the improvements you've made.

Thank you!

Just so you know, Help, About and file details still report the exe as version 1.0.3.0

**Comment by gerritv** [comment]
Oops, this is what happens when you are away from this for almost a year :-( I'll add this to my check list. Thanks.

Fixed in updated 1.0.6.0 Release
