### ISSUE TITLE
Q: alarm when sending manual probe command

### ISSUE THREAD

**Issue by joebananas10** [gerritv/Grbl-Panel#37]
I'm sending a manual probe command "G38.2 Z-50 F10" and sometimes the system returns a
"ALARM: Hard/Soft limit" 
but I am not on any limit. i can still move in both plus and minus Z. See attached image,
![capture](https://cloud.githubusercontent.com/assets/16066344/11610367/dc3b13c0-9b55-11e5-8680-ec991cad87ad.PNG)
Sometimes this manual probe command works with no problem and other times it does not. I can't figure out what causes the difference. How can I find out which limit it's alarming on?

Please advise.

**Comment by gerritv** [comment]
Hi Joe
Grbl 0.9j has some extra status bits to show the causes of Alarms. I am waiting for a new Uno to arrive, my old one didn't want to go into programming mode anymore :-(
Once I receive it I can add support for the new status' into Grbl Panel. In mean time set Verbose to see the stream coming back from Grbl.

**Comment by gerritv** [comment]
$10 needs to be 31 in order to also report Limit pin status. I will figure out a place to display these, probably on RH side where the other Status items are displayed.

**Comment by joebananas10** [comment]
Thanks for the info. I just checked my machine and $10 was set to 255. I changed it to 31 in the Settings grid.
