### ISSUE TITLE
Settings value not being updated

### ISSUE THREAD

**Issue by zahidr** [gerritv/Grbl-Panel#41]
Hi,

I am using  CNC xPRO V2 driver
windows 10
first time user.
New Setting parameter value  are not being updated.
I am going to into filed changing value in settings. 
e.g.  changing $132 from 200 to 80. 
The edit mode pencil image comes up.
I go to different field so that value is changed automatically on the driver board.
Connect , disconnect , the settings parameter value remains default to 200

**Comment by gerritv** [comment]
Hi
To make the setting stick you need to double click in the box where you changed the value. Use the refresh button below that section to get the new values to verify that it worked. 
I think I need to come up with a more obvious way to do this...

Worst case, use the MDI section to enter your command and press Return key or Send button, e.g. $s132=80 in your example.
