### ISSUE TITLE
Joystick

### ISSUE THREAD

**Issue by Encarnacao** [gerritv/Grbl-Panel#54]
how would be possible to implement a joystick to move the cnc machine using grbl?
is there any tutorial in how to achive that?

**Comment by wlaw** [comment]
Most senders like Grbl-Panel allow you to use the keyboard to move the spindle.
Using a program like keytojoy you can assign the keyboard movements to a usb joystick/gamepad.

I use it all of the time and it works well, this was one of the reasons for one of the upgrades.

once you install and test the joystick, install the keytojoy.

Setup your movements, Arrows, PGUP PGDown, +, -, *, /

Just a NOTE. I have to click on a distance for movement or somewhere in that box on grbl-panel to have control.

Good Luck.

**Comment by gerritv** [comment]
@Encarnacao I updated the key mappings in Wiki. I use a joystick with http://www.xpadder.com
