### ISSUE TITLE
tx/rx  won't sinc I have an xpro controller 

### ISSUE THREAD

**Issue by Marklc2015** [gerritv/Grbl-Panel#57]
have a com issue with the software  only shows com 9  at 115200 b ...the controller board flashes green  on Tx . Yellow on Rx ..  when I lower the b rate   I get a green Tx  no Rx 

any help ?

**Comment by gerritv** [comment]
What version of Grbl is running on the Xpro? Any recent version is used at 115200. Any other setting will result is no communication.
GrblPanel won't work with older versions of Grbl.

**Comment by gerritv** [comment]
Closing, no response after 26 days.
