### ISSUE TITLE
Macros - What am I missing?

### ISSUE THREAD

**Issue by aeleus** [gerritv/Grbl-Panel#59]
I'm running GRBL Panel 1.0.9.3 on Windows 10. On the Macros tab, I can create, save, and edit macros. What I don't see is a way to run the macros.

Here's a screenshot of the macros page:
![image](https://cloud.githubusercontent.com/assets/9592641/16358001/84915ffc-3ad4-11e6-830e-104658f4fdac.png)

**Comment by gerritv** [comment]
You should see one or more buttons appear in the top middle section of the front page/screen. Click the appropriate one to run that macro.

**Comment by aeleus** [comment]
I'm afraid that's not happening;

![image](https://cloud.githubusercontent.com/assets/9592641/16548554/4b1d5cc6-415f-11e6-8cd5-5239962c65e7.png)

**Comment by gerritv** [comment]
I will have to look at the code as to why, but I had to click Ok a couple of times for the buttons to show up.

**Comment by gerritv** [comment]
I see 'End' button right below the MDI line on your screen shot?

**Comment by aeleus** [comment]
Doh! How did I miss that?!

Thanks for your help and all the work you've put into GRBL Panel!

**Comment by gerritv** [comment]
:-) It is smallish, and not blinking "Click me, Click me" :-)
