### ISSUE TITLE
Space key Change the function to Hold / Start 

### ISSUE THREAD

**Issue by viewsat** [gerritv/Grbl-Panel#62]
Hi gerritv,
Grbl-Panel 1.0.9.5  space key Change the function to Hold / Start would be better.

![test-2](https://cloud.githubusercontent.com/assets/15762267/17849626/46dd195e-688c-11e6-96d0-508a7786cd56.jpg)

**Comment by gerritv** [comment]
Yes, silly mistake on my part :-( will fix this week.

**Comment by gerritv** [comment]
Fixed, thanks for pointing out my error :-)
