### ISSUE TITLE
Grbl 1.1 laser mode

### ISSUE THREAD

**Issue by tklus** [gerritv/Grbl-Panel#66]
Does this support grbl 1.1 laser mode? Is there a switch or button to turn on and off lasermode? I used to use this sender before I got my laser and loved it. I would like to go back to using it if it supports laser.

Thanks!
Tim

**Comment by gerritv** [comment]
@tklus Yes, please read docs at https://github.com/gnea/grbl/blob/edge/doc/markdown/settings.md
