### ISSUE TITLE
V1.0.9.7 Enhancements Unlock & Reset

### ISSUE THREAD

**Issue by viewsat** [gerritv/Grbl-Panel#67]
Hi,gerritv
Release V1.0.9.7 Enhancements >> Unlock & Reset not changed to red.

![unlock-read](https://cloud.githubusercontent.com/assets/15762267/19378510/a9fc8850-921f-11e6-999b-92491ed2ed66.jpg)

**Comment by gerritv** [comment]
Thanks,
I have a fix but am waiting to release due to some more protocol changes coming. In meantime the workaround is to click Unlock when the Home is crimson.

**Comment by gerritv** [comment]
Fixed in V1.0.9.9
