### ISSUE TITLE
Jog Manual inputs for speed and feed distance

### ISSUE THREAD

**Issue by tklus** [gerritv/Grbl-Panel#69]
Would it be possible, along with the current jog distances and feeds to have a user filled box that we could set the speed of jog and distance other than what is given as the default choices?

there are times I would like to jog the machine 5" or 2" at a time at 150in/min. or maybe faster if the machine supports it.

Just a thought :)

Thanks!
Tim

**Comment by gerritv** [comment]
You can change the defaults on the Settings page?

**Comment by tklus** [comment]
oh yeah! I see now!  Thanks :)
