### ISSUE TITLE
How do I run Grbl-Panel?

### ISSUE THREAD

**Issue by classbproject** [gerritv/Grbl-Panel#76]
This may seem like a noob question but how do I run this? All I can see are .vb files and there does not seem to be any .exe file in here and I couldn't find anything in the Wiki that talks about this.

**Comment by electrokean** [comment]
Go to the Code section above, and up you'll see a label saying "16 releases".  Click that and you'll be able to download a ZIP containing a compiled executable.
Alternatively, download "Visual Studio 2015 Community Edition" from Microsoft, and you can compile (and modify) the VB,Net files yourself.

**Comment by classbproject** [comment]
Got it. Thanks!
