### ISSUE TITLE
tool length offset G43.1

### ISSUE THREAD

**Issue by Mac2712** [gerritv/Grbl-Panel#79]
In the offset sub tab there is a tool length offset G43.1 value box, but there is no means to send a value that you have changed, you can only set it to zero

**Comment by gerritv** [comment]
Doh, I didn't add code to set that :-(. It would seem you are the first to use this. Workaround is f course to send G43.1 z<value> from MDI.
Fix is tested, release soon.

**Comment by Mac2712** [comment]
MDI is what I am using. its great for phantom runs Just haven't sent you a bug report.

As your getting closer to a very polished piece of software, I will start writing down some of my thoughts. I have assess to professional CNC kit so have more exposure to see the good and the bad.

**Comment by gerritv** [comment]
Fixed, thank you for finding this.
