### ISSUE TITLE
Alarm state V1.0.9.10

### ISSUE THREAD

**Issue by Mac2712** [gerritv/Grbl-Panel#85]
When you get an alarm like limit switch, should the status display not say alarm and turn red also reset button turn red?

**Comment by gerritv** [comment]
What does the Status list show? Might have to click on Verbose.

**Comment by Mac2712** [comment]
Morning Gerritv
The Status list shows
Alarm:1
[MSG:Reset to continue]
I also tried a homing timeout
this worked ok, got a Alarm:6 and the Status showed Alarm in red and the unlock turned red
Tried a Probing G38.2 timeout
this worked ok, got a Alarm:5 and the Status showed Alarm in red and the unlock turned red
Don't know any other Alarms to test let me know and I will test them. 
Hope this helps

**Comment by gerritv** [comment]
I think I have them all now, thanks for reporting
