### ISSUE TITLE
Graphical Problems on 1920x1080 screen

### ISSUE THREAD

**Issue by 1Metalguru** [gerritv/Grbl-Panel#86]
With the newer versions of GRBL Panel, running on Windows 7 @1920x1080 resolution,  I have experienced a couple of screen related problems.  This has been a problem on at least the last 2 versions.

1.  The minimize button does not work.  There is no way to minimize the GRBL Panel window.  The only thing I can do to uncover the desktop is to move the window off the side or off the bottom of the screen.  The maximize button works normally

2.  On a 1920x1080 screen, the window is missing the bottom portion.  I can't see the lower part of the window, nor am I able to resize the window.  With the latest release, this appears to have gotten worse, I cannot see anything below the Rapid override buttons.

Update:  I am running my computer with a 50" TV as a monitor.  Since I sit more than 8' away from it, I had the font size set to Large Font (150%).  When I set it back to medium font, I could then see the entire GRBL Panel window.  However, the minimize button problem still exists.  Also, I cannot run this TV with smaller text, as my old eyes refuse to read it.  Being able to resize the window would certainly help.

And no, this TV is not in my shop.  I run it with an arduino plugged in so I can assist customers with software questions.

MG

![image](https://cloud.githubusercontent.com/assets/24995035/21754178/1e71fdce-d5b8-11e6-997b-a79e8272b517.png)

**Comment by gerritv** [comment]
The minimize button will re-appear in the next release.
I will attempt to reproduce your other situation, thank you for the clear details. My secondary monitor is 1920x1080 so fingers crossed.

The screen size was locked due to laser users maximizing the display and then complaining that their execution rate was slowing down. This was due to having to update more lines on the Gcode list. Tough to please everyone :-(

**Comment by Mac2712** [comment]
I have 2 PC with 1920X1080 monitor and GRBL panel fits easily into the screen in fact 1 1/2 times. I would suggest you check you screen setup ie correct driver for both graphics card and monitor and you have the font size set to 100%.
Hope this helps
