### ISSUE TITLE
sudenly GRBL panel stop working, do not know why :(

### ISSUE THREAD

**Issue by davidcnc** [gerritv/Grbl-Panel#91]
I do not know what happened, may be some update of windows 7, may be I accidentally delete something, but today I run panel and it stops at this window :(
![img_7639](https://cloud.githubusercontent.com/assets/25524187/22583599/06585aea-ea07-11e6-9e75-2fa9e9324a85.JPG)

**Comment by gerritv** [comment]
I am guessing by what I can spot on the display that this is on start up?
If you click on details I might get a location of the error. Did you by change update Grbl on the Arduino? What version of Grbl and GrblPanel are you using?
