### ISSUE TITLE
Malfunctions program

### ISSUE THREAD

**Issue by AutoRich** [gerritv/Grbl-Panel#92]
It was noted several problems:
1. During operation, the program covers more than 50% of CPU resources (AMD processor 3000 MHz, 2 cores).
2. Sometimes the program stops with an error. At the same time on the Work tab in the display field XYZ coordinates is displayed the number of large numbers, such as 54, and under it - a small 54.150 (unfortunately could not make a screenshot). I shoot a tick - Pause on error and Status Poll - coordinates in the fields are not displayed, is now testing a program without them. Changed USB cable, changed the COM port, changed power supplies - but the problem has not been resolved.
I understand - the program gets the current position of the Arduino and outputs in the field XYZ and if these data have some error, it causes a failure in the program. How it is possible to disable the transmission of these coordinates from the Arduino?
Make it so that when a tick is removed Status Poll, in the field XYZ coordinates were derived passed to the Arduino.

**Comment by gerritv** [comment]
I can't reproduce seeing 50% CPU, most I see is 9%.

Re: stopping with error. There is not much I can do. Grbl will always send those updates unless you alter Grbl's code. I don't recall the previous Issue that you raised but changing the com port is not likely to solve your data loss. It is more likely electrical noise or it is one of the bad serial<>USB chips like CH340 on the Arduino board.
On Settings page, uncheck Status Poll results in never asking for status from Grbl. Grbl will still send 'ok' when a command completes. If even that gives crashes etc, then there is nothing I can do in code to solve that.
