### ISSUE TITLE
How to change baud rate

### ISSUE THREAD

**Issue by Tom-Nelson** [gerritv/Grbl-Panel#93]
Not an issue as much as a question. 
How do I change the baud rate in GRBL Panel. Tried just typing a new baud rate into the baud rate window, as well as in GrblPanel.exe.config
</setting>
            <setting name="Baud" serializeAs="String">
                <value>38400</value>
            </setting>
but still can't connect. 
I know the Arduino baud rate is right because I can connect to it via the IDE console.(Note - this is via direct USB, not via USB-serial converter )

**Comment by gerritv** [comment]
For now the workaround is to edit the user.config file. It is located in c:/users/<yourusername>/AppData/local/GrblPanel. There will be one or more directories there. Find the one with .13 in the name. Edit the Baud rate value to 38400. Start GrblPanel and you will see 38400 selected.
