### ISSUE TITLE
Arrow keys doesn't work!

### ISSUE THREAD

**Issue by adibiut** [gerritv/Grbl-Panel#94]
Hi. I'm using v1.0.9.13
Left, right, up, Page up and Page Down doesn't work (I can't move axes with keyboard)
but other keys work well! (/ * + - A X Y Z Ctrl+F,H,...)
What's wrong?

**Comment by gerritv** [comment]
Check the box on Settings page?

**Comment by adibiut** [comment]
@gerritv  Thanks. I didn't know there's a checkbox
