### ISSUE TITLE
Jogging not working

### ISSUE THREAD

**Issue by NAIRB35** [gerritv/Grbl-Panel#97]
When jogging the panel adds $J=G91G20X0.1 F50 and we get an error:Bad number format.
How do I correct this?

**Comment by gerritv** [comment]
Grbl version? Is Spindle speed set?

**Comment by NAIRB35** [comment]
We are using it on the Inventables X-carve.
Grbl Version 1.0c
Spindle speed is set.
It happens on all axis.
No indication for Idle,Jog only Alarm.

**Comment by gerritv** [comment]
1.0c is ancient, lots of changes since then. I recommend that you upgrade.
I should probably add a pop up indicating unsupported for anything less than 0.9h or 1.1.
