### ISSUE TITLE
How to use Grbl-Panel in Windows XP

### ISSUE THREAD

**Issue by kefeur** [gerritv/Grbl-Panel#98]
Error message: do not win32 application.
How can I use windows xp with the Grbl-Panel?
Not compatibile?
What is the solution.
Thank you in advance the answer.

**Comment by gerritv** [comment]
If you can install .Net 4.5.2 on XP then it will run. I no longer have XP, nor Win 7 machines to test on.

**Comment by kefeur** [comment]
XP SP3 not compatibile Net 4.5.2 -

**Comment by gerritv** [comment]
Bummer. Time to move up to 7 at least then.

**Comment by kefeur** [comment]
Yes, it will be 7.
Thank you.
